### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by Taz03** [losier/Xenon#83]
![image](https://user-images.githubusercontent.com/73871477/210184316-d58ca715-9e9b-4177-9df8-aa88676a7581.png)
based??

**Comment by losier** [comment]
> ![image](https://user-images.githubusercontent.com/73871477/210184316-d58ca715-9e9b-4177-9df8-aa88676a7581.png)
> based??

Lol my bad thanks though will change it soon sorry haha
